package list and scripts: updates for openSUSE Tumbleweed

diff --git a/qa/admin/check-other b/qa/admin/check-other
--- a/qa/admin/check-other
+++ b/qa/admin/check-other
@@ -15,6 +15,14 @@ then
     exit 1
 fi
 
+if [ ! -f $home/packages.rc ]
+then
+    echo >&2 "Botch: cannot find $home/packages.rc"
+    exit
+fi
+
+. $home/packages.rc
+
 cd "$home" || exit
 home=`pwd`
 
@@ -67,45 +75,7 @@ rm -f $tmp/*
 ./old-list-packages -R $opts_v || exit
 mv tmp.* $tmp
 
-# copied from post-setup ...
-#
-pkg_env=""
-if which apt-get >/dev/null 2>&1
-then
-    pkg_type=dpkg
-elif which zypper >/dev/null 2>&1
-then
-    pkg_type=rpm
-elif which dnf >/dev/null 2>&1
-then
-    pkg_type=rpm
-elif which yum >/dev/null 2>&1
-then
-    pkg_type=rpm
-elif which pacman >/dev/null 2>&1
-then
-    pkg_type=pacman
-elif which pkg >/dev/null 2>&1
-then
-    pkg_type="pkg"
-# pkgin has to be before pkg_add in this compound
-# if-elif-elif-else-fi because NetBSD has both and we need
-# to use pkgin for NetBSD
-#
-elif which pkgin >/dev/null 2>&1
-then
-    pkg_type="pkgin"
-elif which pkg_add >/dev/null 2>&1
-then
-    pkg_type="pkg_add"
-elif which slackpkg >/dev/null 2>&1
-then
-    pkg_type="slackpkg"
-else
-    echo >&2 "Botch: need recipe for system package type"
-    exit
-fi
-$debug && echo "Debug: package type: $pkg_type"
+_get_pkg_type
 
 _find()
 {
