package-list updates from OpenMandriva and others
- list-packages: serious overhaul and some refactoring
- old-list-packages: rework
- other-packages/*: updates
- package-lists/new: improvements but this is still not bullet proof
- packages.rc: refactor to get some more common functions in here
- others: need to lean about OpenMandriva
- updated package lists for a handful of other platforms

diff --git a/qa/admin/list-packages b/qa/admin/list-packages
--- a/qa/admin/list-packages
+++ b/qa/admin/list-packages
@@ -11,7 +11,7 @@ _usage()
     echo >&2 
     echo >&2 "  -A arch      override platform arch"
     echo >&2 "  -D distro    override platform distro"
-    echo >&2 "  -c           check packing list"
+    echo >&2 "  -c           check package list"
     echo >&2 "  -i tag       include only lines with a tag"
     echo >&2 "  -m           list only missing packages"
     echo >&2 "  -n           report my packing-list file and quit"
@@ -41,7 +41,7 @@ _fmt()
 }
 
 # on entry we have ...
-# $tmp.list - packages from packing list, with optional -x and -i processing
+# $tmp.list - packages from package list, with optional -x and -i processing
 # 	done
 # $tmp.allpkgs - all available packages for this platform
 #
@@ -82,7 +82,7 @@ _do_check()
     #
     cat <<End-of-File >$tmp.tags
 dpkg	Ubuntu Debian LinuxMint MX
-rpm	RHEL Fedora CentOS openSUSE SUSE SLES AmazonLinux
+rpm	RHEL Fedora CentOS openSUSE SUSE SLES OpenMandriva-Lx AmazonLinux
 emerge	Gentoo
 pkgin	NetBSD
 pkg_add	OpenBSD
@@ -92,16 +92,59 @@ slackpkg	Slackware
 pacman	ArchLinux
 brew	Darwin
 End-of-File
-    tag=`sed -n <$tmp.tags -e 's/	/ /g' -e 's/$/ /' -e "/ $distro /s/ .*//p"`
-    if [ -z "$tag" ]
+    pkg_mgr_tag=`sed -n <$tmp.tags -e 's/	/ /g' -e 's/$/ /' -e "/ $distro /s/ .*//p"`
+    if [ -z "$pkg_mgr_tag" ]
     then
-	echo >&2 "Botch: can't get manifest tag for \"$distro\""
+	echo >&2 "Botch: can't get manifest package manager tag for \"$distro\""
 	exit
     fi
+    $verbose && echo >&2 "Info: pkg_mgr_tag=$pkg_mgr_tag"
+
+    # tests here are copied from whatami
+    #
+    iam=''
+    if [ -f /etc/SuSE-release ]
+    then
+	iam=suse
+    elif [ -f /etc/centos-release ]
+    then
+	iam=centos
+    elif [ -f /etc/mandriva-release ]
+    then
+	iam=mandriva
+    elif [ -f /etc/redhat-release ]
+    then
+	iam=redhat
+    elif [ -f /etc/debian_version ]
+    then
+	iam=debian
+    elif [ -f /etc/gentoo-release ]
+    then
+	iam=gentoo
+    elif [ -f /etc/fedora-release ]
+    then
+	iam=fedora
+    elif [ -f /etc/os-release ]
+    then
+	iam=opensuse
+    elif [ -f /etc/release ]
+    then
+	iam=openindiana
+    elif [ -f /etc/slackware-version ]
+    then
+	iam=slackware
+    elif [ -f /etc/arch-release ]
+    then
+	iam=arch
+    elif [ -f /etc/lsb-release ]
+    then
+	iam=`sed </etc/lsb-release -n -e '/^DISTRIB_ID *= */s///p' | tr '[A-Z]' '[a-z]'`
+    fi
+    $verbose && echo >&2 "Info: iam=$iam"
 
     rm -f $tmp.matched
     awk <$home/other-packages/manifest '{ print NR ":" $0 }' \
-    | grep ":$tag?" \
+	| grep -E ":($pkg_mgr_tag|$iam)\?" \
     | sed \
 	-e 's/[ 	]*#.*//' \
 	-e 's/:[^[]*\[/ /' \
@@ -147,7 +190,7 @@ BEGIN		{ sts=1 }
 			print $0 >>"'$tmp.matched'"
 			sts=0
 			# keep going because there may be more than one package
-			# in the packing list that matches the pattern in the
+			# in the package list that matches the pattern in the
 			# manifest, e.g. may need to have 2 versions of a pkg
 		    }
 		  }
@@ -163,7 +206,7 @@ END		{ exit sts }'
 		    then
 			echo "$pkg" >>$tmp.del
 		    else
-			echo "manifest:$lineno $pkg: in packing list, but not available?"
+			echo "manifest:$lineno $pkg: in package list, but not available?"
 		    fi
 		else
 		    touch $tmp.ok
@@ -188,10 +231,11 @@ END		{ exit sts }'
 		for skip_pkg in `cat $tmp.skip`
 		do
 		    skip_pkg_re=`echo "$skip_pkg" | sed -e 's;/;\\\\/;g'`
+		    #debug# echo "pkg=$pkg skip_pkg=$skip_pkg skip_pkg_re=$skip_pkg_re" 
 		    if echo "$pkg" | awk '
 BEGIN		{ sts=1 }
 		{ for (i = 1; i <= NF; i++) {
-		    if ($i == "'"$skip_pkg"'" || $i ~ /^'"$skip_pkg_re"'$/) {
+		    if ($i == "'"$skip_pkg"'" || $i ~ /^'"$skip_pkg_re"'$/ || "'"$skip_pkg"'" ~ $i) {
 			sts=0
 			exit
 		    }
@@ -236,32 +280,51 @@ END		{ exit sts }'
 			    then
 				if $update
 				then
-				    echo "$pkg" >>$tmp.add
+				    # special hack for perl-Foo-Bar, don't add
+				    # if Foo::Bar cpan already in package list
+				    #
+				    case "$pkg"
+				    in
+					perl-*)
+					    xxx=`echo "$pkg" | sed -e 's/perl-//' -e 's/-/::/g'`
+					    if grep -q "^$xxx cpan" $tmp.orig >//dev/null
+					    then
+						$verbose && echo >&2 "Info: skip missing $pkg because $xxx cpan already in package list"
+						pkg=''
+					    fi
+					    ;;
+				    esac
+				    [ -n "$pkg" ] && echo "$pkg" >>$tmp.add
 				else
 				    if [ "$avail" = "$installed" ]
 				    then
-					echo "manifest:$lineno $pkg: not in packing list, but already installed?"
+					echo "manifest:$lineno $pkg: not in package list, but already installed?"
 				    else
-					echo "manifest:$lineno $pkg: not in packing list, but available?"
+					echo "manifest:$lineno $pkg: not in package list, but available?"
 				    fi
 				fi
 			    else
 				navail=`echo "$avail" | wc -w | sed -e 's/ //g'`
 				if [ "$navail" -eq 1 ]
 				then
-				    if [ "$avail" = "$installed" ]
+				    if $update
 				    then
-					echo "manifest:$lineno $pkg: not in packing list, but $avail already installed?"
+					echo "$avail" >>$tmp.add
 				    else
-					echo "manifest:$lineno $pkg: not in packing list, but $avail available?"
+					if [ "$avail" = "$installed" ]
+					then
+					    echo "manifest:$lineno $pkg: not in package list, but $avail already installed?"
+					else
+					    echo "manifest:$lineno $pkg: not in package list, but $avail available?"
+					fi
 				    fi
 				elif [ "$navail" -le 2 ]
 				then
 				    # don't try already installed here ... it is too hard!
 				    #
-				    echo "manifest:$lineno $pkg: not in packing list, but `echo "$avail" | tr '\012' ' ' | sed -e 's/ $//' -e 's/ / and /'` available?"
+				    echo "manifest:$lineno $pkg: not in package list, but `echo "$avail" | tr '\012' ' ' | sed -e 's/ $//' -e 's/ / and /'` available?"
 				else
-				    echo "manifest:$lineno $pkg: not in packing list, but `echo "$avail" | tr '\012' ' ' | sed -e 's/ .* \([^ ][^ ]*\) / ... \1/'` available?"
+				    echo "manifest:$lineno $pkg: not in package list, but `echo "$avail" | tr '\012' ' ' | sed -e 's/ .* \([^ ][^ ]*\) / ... \1/'` available?"
 				fi
 			    fi
 			fi
@@ -279,11 +342,16 @@ END		{ exit sts }'
 	then
 	    : OK
 	else
-	    echo "$pkg: required but not in packing list"
+	    if $update
+	    then
+		echo "$pkg" >>$tmp.add
+	    else
+		echo "$pkg: required but not in package list"
+	    fi
 	fi
     done
 
-    # and are all the packages in the packing list really available?
+    # and are all the packages in the package list really available?
     #
     sed <$tmp.list -e '/cpan(/d' -e '/pip3(/d' \
     | tr '|' '\012' \
@@ -296,12 +364,12 @@ END		{ exit sts }'
 	    then
 		echo "$pkg" >>$tmp.del
 	    else
-		echo "$pkg: in packing list but not available"
+		echo "$pkg: in package list but not available"
 	    fi
 	fi
     done
 
-    # and does the packing list contain lines that do not match the
+    # and does the package list contain lines that do not match the
     # manifest?
     if [ -s $tmp.matched ]
     then
@@ -311,18 +379,18 @@ END		{ exit sts }'
 	comm -23 $tmp.list $tmp.matched >$tmp.no-manifest
 	if [ -s $tmp.no-manifest ]
 	then
-	    echo "In packing list, but not in manifest ..."
+	    echo "In package list, but not in manifest ..."
 	    _fmt 72 <$tmp.no-manifest | sed -e 's/^/    /'
 	fi
     fi
 
-    # any duplicates in the packing list are also a problem
+    # any duplicates in the package list are also a problem
     #
     sort $tmp.list | uniq -c \
     | sed -e '/^ *1 /d' -e 's/^ *[0-9][0-9]* //' >$tmp.dup
     if [ -s $tmp.dup ]
     then
-	echo "Duplicated in packing list ..."
+	echo "Duplicated in package list ..."
 	_fmt 72 <$tmp.dup | sed -e 's/^/    /'
     fi
 }
@@ -514,6 +582,7 @@ then
 else
     cat "$home/package-lists/${distro}+${version}+${arch}"
 fi >$tmp.list
+cp $tmp.list $tmp.orig
 
 if $missing || $check
 then
@@ -530,7 +599,7 @@ then
 	    apt-cache dumpavail | sed -n -e '/^Package: /s///p' >$tmp.allpkgs
 	    ;;
 
-	RHEL|Fedora|CentOS|openSUSE|SUSE\ SLES|OpenMandriva|AmazonLinux)
+	RHEL|Fedora|CentOS|openSUSE|SUSE\ SLES|OpenMandriva-Lx|AmazonLinux)
 	    rpm -qa --qf '%{NAME}\n' >$tmp.installed
 	    if which zypper >/dev/null 2>&1
 	    then
@@ -825,7 +894,7 @@ then
 	# special handling for Arch Linux (pacman) naming of packages
 	# pacman -Qi (for tmp.installed) => gcc
 	# pacman -Ss (for tmp.allpkgs) => core/gcc
-	# and our packing list (tmp.list) uses the longer form ... so cull
+	# and our package list (tmp.list) uses the longer form ... so cull
 	# the prefix on the assumption that the probability of a name
 	# collision is really small, but then we need to do the matching
 	# the hard way to generate a list with the full package names
@@ -851,9 +920,9 @@ then
 	if $very_verbose
 	then
 	    echo >&2 "Required:"
-	    cat $tmp.1 >&2
+	    _fmt 72 <$tmp.1 | sed -e 's/^/    /' >&2
 	    echo >&2 "Installed:"
-	    cat $tmp.2 >&2
+	    _fmt 72 <$tmp.2 | sed -e 's/^/    /' >&2
 	fi
 	comm -23 $tmp.1 $tmp.2 >$tmp.tmp
 	# now we may have alternates installed ...
diff --git a/qa/admin/old-list-packages b/qa/admin/old-list-packages
--- a/qa/admin/old-list-packages
+++ b/qa/admin/old-list-packages
@@ -20,6 +20,7 @@ _usage()
     echo "  -p           generate list of likely packages that should be"
     echo "               installed with dnf or apt-get or yum or ..."
     echo "  -P           same as -p, but emit shell commands for installer"
+    echo "  -R           raw ... generate parsed tmp.* files"
     echo "  -r require   use alternative require file"
     echo "  -s skip      use alternative skip file"
     echo "  -S skipbase  use alternative basename for skipbase.<hostname> files"
@@ -88,7 +89,7 @@ _build_allpkgs()
 	apt-cache dumpavail | sed -n -e '/^Package: /s///p' >$tmp.allpkgs
 	;;
 
-    RHEL|Fedora|CentOS|openSUSE|SUSE\ SLES|OpenMandriva|AmazonLinux)
+    RHEL|Fedora|CentOS|openSUSE|SUSE\ SLES|OpenMandriva-Lx|AmazonLinux)
 	if which zypper >/dev/null 2>&1
 	then
 	    zypper --no-refresh packages 2>&1 \
@@ -164,7 +165,7 @@ p
 
     *)
 	echo >&2 "Botch: _build_allpkgs(): no recipe for $distro"
-	exit 1
+	exit
 	;;
 
     esac
@@ -388,7 +389,7 @@ home=`echo $0 | sed -e 's/\/*old-list-packages$//'`
 if [ ! -f $home/whatami ]
 then
     echo >&2 "Botch: \$0=$0 -> bad \$home=$home ?"
-    exit 1
+    exit
 fi
 
 if [ ! -f $home/packages.rc ]
@@ -414,11 +415,12 @@ check_manifest_args=''
 manifest="$home"/other-packages/manifest		# default, see -m
 otherdir=other-packages					# default, see -o
 require="$home"/other-packages/require			# default, see -r
+raw=false
 skip="$home"/other-packages/skip			# default, see -s
 skipbase="$home"/other-packages/skip			# default, see -S
 unavailable="$home"/other-packages/unavailable		# default, see -u
 include_meta=true
-while getopts 'abcfm:Mo:pPr:s:S:u:v?' p
+while getopts 'abcfm:Mo:pPr:Rs:S:u:v?' p
 do
     case "$p"
     in
@@ -464,6 +466,15 @@ do
 		require="$OPTARG"
 		;;
 
+	R)	# raw tmp.* files generated
+		if $very_verbose
+		then
+		    echo >&2 "Error: cannot use -R with -v -v"
+		    exit
+		fi
+		raw=true
+		;;
+
 	s)	# alternate skip
 		skip="$OPTARG"
 		;;
@@ -478,6 +489,11 @@ do
 
 	v)	if $verbose
 		then
+		    if $raw
+		    then
+			echo >&2 "Error: cannot use -v -v with -R"
+			exit
+		    fi
 		    very_verbose=true
 		else
 		    verbose=true
@@ -492,12 +508,13 @@ done
 shift `expr $OPTIND - 1`
 [ $# -eq 0 ] || _usage
 
-if $very_verbose
+sts=1
+if $very_verbose || $raw
 then
     tmp=tmp
 else
     tmp=${TMPDIR:-/tmp}/old-list-packages-$$
-    trap "rm -f $tmp.*; exit 0" 0 1 2 3 15
+    trap "rm -f $tmp.*; exit \$sts" 0 1 2 3 15
 fi
 rm -f $tmp.*
 
@@ -537,17 +554,17 @@ then
 fi
 if [ ! -f "$require" ]
 then
-    echo 2>&1 "Botch: cannot find require: $require"
+    echo >&2 "Botch: cannot find require: $require"
     exit 1
 fi
 if [ ! -f "$unavailable" ]
 then
-    echo 2>&1 "Botch: cannot find unavailable: $unavailable"
+    echo >&2 "Botch: cannot find unavailable: $unavailable"
     exit 1
 fi
 if [ ! -f "$skip" ]
 then
-    echo 2>&1 "Botch: cannot find skip: $skip"
+    echo >&2 "Botch: cannot find skip: $skip"
     exit 1
 fi
 
@@ -587,7 +604,7 @@ in
 	| sed -n -e '/ installed$/s/ .*//p' >$tmp.installed
 	;;
 
-    RHEL|Fedora|CentOS|openSUSE|SUSE\ SLES|OpenMandriva|AmazonLinux)
+    RHEL|Fedora|CentOS|openSUSE|SUSE\ SLES|OpenMandriva-Lx|AmazonLinux)
 	mytype=rpm
 	if which zypper >/dev/null 2>&1
 	then
@@ -653,17 +670,17 @@ in
 esac
 if [ -z "$mytype" ]
 then
-    echo 2>&1 "$0: Botch: don't recognize mytype for: $distro"
+    echo >&2 "$0: Botch: don't recognize mytype for: $distro"
     exit
 fi
 if [ -z "$installcmd" ]
 then
-    echo 2>&1 "$0: Botch: don't recognize installcmd for: $distro"
+    echo >&2 "$0: Botch: don't recognize installcmd for: $distro"
     exit
 fi
 if [ ! -f $tmp.installed ]
 then
-    echo 2>&1 "$0: Botch: can't generate tmp.installed for: $distro"
+    echo >&2 "$0: Botch: can't generate tmp.installed for: $distro"
     exit
 fi
 
@@ -735,6 +752,7 @@ then
     echo >&2 "Warning: don't understand what packing is being used here ..."
     echo >&2 "         it is none of: $pkgtypes"
 fi
+rm -f $tmp.ok
 
 # Strip the distro-dependent lines that do not apply ...
 # this is an optimization remove checks from the main loop below
@@ -748,15 +766,15 @@ then
 elif [ -f /etc/centos-release ]
 then
     iam=centos
+elif [ -f /etc/mandriva-release ]
+then
+    iam=mandriva
 elif [ -f /etc/redhat-release ]
 then
     iam=redhat
 elif [ -f /etc/debian_version ]
 then
     iam=debian
-elif [ -f /etc/mandriva-release ]
-then
-    iam=mandriva
 elif [ -f /etc/gentoo-release ]
 then
     iam=gentoo
@@ -813,10 +831,10 @@ mv $tmp.tmp $tmp.manifest
 # the "unavailable" file records packages that are not available for a
 # particular distribution and version and architecture ... 
 #
-_parse_file $unavailable >$tmp.pkgs
-if [ -s $tmp.pkgs ]
+_parse_file $unavailable >$tmp.unavailable
+if [ -s $tmp.unavailable ]
 then
-    unavail_pkg="`cat $tmp.pkgs`"
+    unavail_pkg="`cat $tmp.unavailable`"
 fi
 $very_verbose && echo >&2 "unavailable: $unavail_pkg"
 
@@ -824,10 +842,10 @@ $very_verbose && echo >&2 "unavailable: $unavail_pkg"
 # particular distribution and version and archtecture ... 
 #
 require_pkg=''
-_parse_file $require >$tmp.pkgs
-if [ -s $tmp.pkgs ]
+_parse_file $require >$tmp.require
+if [ -s $tmp.require ]
 then
-    $very_verbose && echo >&2 "require: `cat $tmp.pkgs`"
+    $very_verbose && echo >&2 "require: `cat $tmp.require`"
     for _need in `cat $tmp.pkgs`
     do
 	if grep "^$_need\$" $tmp.installed >/dev/null
@@ -888,7 +906,7 @@ then
     $verbose && echo >&2 "Processing $skipbase.`hostname -s` ..."
     skip_pkg=`sed <$skipbase.$_hostname \
 	    -e 's/#.*//' \
-	    -e '/^[ 	]*$/d' | tr '\012' ' '`
+	    -e '/^[ 	]*$/d' | tr '\012' ' ' | tee $tmp.skip.$_hostname`
     if [ -n "$skip_pkg" ]
     then
 	$very_verbose && echo >&2 "skip on host: $skip_pkg"
@@ -903,11 +921,11 @@ fi
 # the "skip" file records packages that should NOT be installed for a
 # particular distribution and version and architecture ... 
 #
-_parse_file $skip >$tmp.pkgs
+_parse_file $skip >$tmp.skip
 if [ -s $tmp.pkgs ]
 then
-    $very_verbose && echo >&2 "skip: `cat $tmp.pkgs`"
-    skip_pkg="$skip_pkg `cat $tmp.pkgs`"
+    $very_verbose && echo >&2 "skip: `cat $tmp.skip`"
+    skip_pkg="$skip_pkg `cat $tmp.skip`"
     for _pkg in `cat $tmp.pkgs`
     do
 	_cull_from_manifest "$_pkg" SKIP
@@ -981,6 +999,17 @@ fi
 # as appropriate.
 #
 _build_allpkgs
+
+if $raw
+then
+    # for -R we're all done
+    #
+    echo "Created ..."
+    echo $tmp.*
+    sts=0
+    exit
+fi
+
 rm -f $tmp.sed
 sed <$tmp.manifest \
     -e 's/[^[]*\[//' \
@@ -1386,7 +1415,13 @@ then
     fi
 fi
 
-$pkglist && exit
+if $pkglist
+then
+    # for -p we'r all done
+    #
+    sts=0
+    exit
+fi
 
 # Any required packages not installed?
 #
@@ -1486,3 +1521,5 @@ End-of-File
 fi
 
 $very_verbose && echo >&2 "temp files:" $tmp.*
+
+sts=0
diff --git a/qa/admin/pcp-daily b/qa/admin/pcp-daily
--- a/qa/admin/pcp-daily
+++ b/qa/admin/pcp-daily
@@ -186,12 +186,19 @@ then
     qa/admin/list-packages -m -x cpan -x pip3 >\$tmp.tmp
     if [ -s \$tmp.tmp ] && [ -f qa/admin/install-packages ]
     then
-	echo "Info: installing missing system packages: \`cat \$tmp.tmp\`" | tee -a \$HOME/daily.log
-	if ! qa/admin/install-packages \`cat \$tmp.tmp\`
-	then
-	    echo "Error: installing missing system packages failed" | tee -a \$HOME/daily.log
-	    exit
-	fi
+	case \`hostname\`
+	in
+	    vm*)
+		echo "Info: installing missing system packages: \`cat \$tmp.tmp\`" | tee -a \$HOME/daily.log
+		if ! qa/admin/install-packages \`cat \$tmp.tmp\`
+		then
+		    echo "Error: installing missing system packages failed" | tee -a \$HOME/daily.log
+		    exit
+		fi
+		;;
+	    *)
+		echo "Info: not a vm* host, so skip installing missing system packages" | tee -a \$HOME/daily.log
+	esac
     fi
 fi
 ok=false
